### ISSUE TITLE
Plexamp 3.4.4 is available

### ISSUE THREAD

**Issue by owendaprile** [flathub/com.plexamp.Plexamp#1]
See the forum post here: https://forums.plex.tv/t/plexamp-release-notes/221280/26

**Comment by hdonnay** [comment]
Thanks for pointing out the release. I guess I'll just have to subscribe to that thread.

**Comment by nedrichards** [comment]
That works, it may also be susceptible to [flatpak-external-data-checker](https://github.com/flathub/flatpak-external-data-checker) which could make a PR (which would then kickoff a build for testing) for you.

**Comment by hdonnay** [comment]
It looks like there's a file that's used by the SPA to make the download link: https://plexamp.plex.tv/plexamp.plex.tv/desktop/latest-linux.yml

However, it looks like flatpak-external-data-checker doesn't have a handler that'd work to construct the download URL.

**Comment by hdonnay** [comment]
it looks like the html updater can be press-ganged into working, so I'll see if I can get that wired up.
