### ISSUE TITLE
Plexamp defaults to XWayland when running under wayland session

### ISSUE THREAD

**Issue by 4ndv** [flathub/com.plexamp.Plexamp#135]
```shell
$ echo $XDG_SESSION_TYPE
wayland
$ flatpak run com.plexamp.Plexamp                 
Wayland socket not available, running through Xwayland.
```

But when I'm explicitly pass `--socket=wayland` it runs fine:

```shell
$ flatpak run --socket=wayland com.plexamp.Plexamp   
Wayland socket is available, running natively on Wayland.
```

When running via desktop shortcut, app always runs via XWayland, with no obvious way to pass required arg.

Also, maybe related to #126?

**Comment by simonxciv** [comment]
We intentionally disabled Wayland by default, as Electron+Wayland is broken in many cases (e.g. specific LTS distros, certain NVIDIA cards etc).

For now, xwayland provides a much more reliable and consistent experience.

Please also note: this repository's issues are mostly unmonitored. For support, issues, or requests, please use the Plex Forums in future.

**Comment by 4ndv** [comment]
Thank you for reply!

I've reenabled it myself via Flatseal, in case anyone will find this issue
