### ISSUE TITLE
screenshot too small for flathub website

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.plexamp.Plexamp#2]
Checking why the screenshot was broken on the flathub website I saw that it was being discarded as too small (from https://flathub.org/builds/#/builders/8/builds/4914 )

> com.plexamp.Plexamp:               Failed to download https://raw.githubusercontent.com/flathub/com.plexamp.Plexamp/master/plexamp_1.png: com.plexamp.Plexamp-plexamp_1.png is too small to be used: 270x475

Looks like we need a larger screenshot. It's an interesting case as the build should fail in a more obvious way for you

**Comment by hdonnay** [comment]
I think I fixed this.
