### ISSUE TITLE
Upstream incoming

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.plexamp.Plexamp#25]
@hdonnay the Plex team have asked to take over plexamp on flathub. Following our [upstream takeover process](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do) in the next few days we will be adding them to this repo, if you want to send patches you'll need to send a PR from then on.

I believe that they want to migrate the app-id but that should be pretty seamless.

**Comment by hdonnay** [comment]
I see @simonxciv from Plex (:wave:) has landed a grip of commits, going to close this.
