### ISSUE TITLE
Flatpak depends on outdate and unsafe runtime org.freedesktop.Platform 21.08

### ISSUE THREAD

**Issue by jimtuttle** [flathub/com.plexamp.Plexamp#87]
The flatpak depends on org.freedesktop.Platform branch 21.08, which is end of life and no longer receiving fixes or security updates.  This is clear in when running flatpak update:

`Info: runtime org.freedesktop.Platform branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   com.plexamp.Plexamp`

`Info: runtime org.freedesktop.Platform.GL.default branch 21.08 is end-of-life, with reason:
   org.freedesktop.Platform 21.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this extension:
   com.plexamp.Plexamp`

It's also emphatically noted on [flatpak.org](https://flathub.org/apps/com.plexamp.Plexamp):
`Legacy windowing system: Uses a legacy windowing system
Uses an end-of-life runtime: The runtime used by this app is no longer receiving security updates`

**Comment by FlorianLaunay** [comment]
@simonxciv is it possible to upgrade to branch 23.08 by the next release ?

**Comment by hdonnay** [comment]
I tried building this on `23.08`, but it coredumps. I can post the coredump somewhere if needed, but I can't really debug this because the libraries seem to be stripped.

**Comment by avLightless** [comment]
> I tried building this on `23.08`, but it coredumps. I can post the coredump somewhere if needed, but I can't really debug this because the libraries seem to be stripped.

Can confirm, tried building it with both `22.08` and `23.08`.

**Comment by hdonnay** [comment]
So I decided to dig into this more.

I jumped into a debug sandbox and ran strace such that it would log for all forked processes:
```
% flatpak-builder --run build-dir com.plexamp.Plexamp.yaml strace -o strace -ff /app/bin/startplexamp
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --enable-features=UseSkiaRenderer
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 18:18:53.249: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:18:53.251: Failed to load module "canberra-gtk-module"
Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml
[6:1213/181853.266884:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[6:1213/181853.266993:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Main: restoring window state from /var/home/hank/.var/app/com.plexamp.Plexamp/config/Plexamp/window-state-plexamp-main.json
Started Media Service: false
Linux: Registering MPRIS service.
[6:1213/181854.063922:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[6:1213/181854.064023:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[6:1213/181854.064142:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[6:1213/181854.064237:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[6:1213/181854.064328:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
APPIMAGE env is not defined, current application is not an AppImage
Error: Render process (Plexamp) crashed (139) :(
Quitting...
```

I know the process segfaults, because that's what I can see in `coredumpctl`, so we need to see which process actually had the signal delivered:

```
% grep -e '--- SIGSEGV' strace.*
strace.114:--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1000001b7} ---
```

It's process 114 on this run, so looking at the trace, I can see that it crashes after doing a read from fd 51:
```
read(51, "\32\23\n\16\335\366\203\311\204%\270]\n\322\312=:\207\2078GJ\0163\16j\31\360\246\177R\371", 32) = 32
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x1000001b7} ---
```

Looking at the `openat`, `socket`, and `connect` calls made, it looks like this process is reading a `cacert.pem` and making HTTPS connections. For our specific fd, it's:
```
socket(AF_INET, SOCK_STREAM, IPPROTO_TCP) = 51
connect(51, {sa_family=AF_INET, sin_port=htons(443), sin_addr=inet_addr("104.18.41.153")}, 16) = -1 EINPROGRESS (Operation now in progress)
```

and the pem file:
```
openat(AT_FDCWD, "/app/bin/plexamp/resources/cacert.pem", O_RDONLY) = 73
```

The other file in that `resources` directory is a for an update check that lists `plexamp.plex.tv`. I have a hunch...
```
% dig +short plexamp.plex.tv
172.64.146.103
104.18.41.153
```

So this process looks to be reaching out for an update check. What if I just remove that file?
Seems to run fine. Can probably remove the whole update config, as Plexamp can't self-update anyway.

I'll send a PR with a fix soon.

**Comment by Lamera** [comment]
@simonxciv Is there any progress on this issue?
